djangoProject3(Task Manager)/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # A path for the admin page.
    path('admin/', admin.site.urls),
    path('', include('taskly.urls')),
]

taskly/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


# A list of url patterns.
app_name = "taskly"
urlpatterns = [
    # The default page that will be displayed when you go to the root of the website.
    path('', views.index, name='dashboard'),

    # An url for logging out, links in views and logout.html
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # An url for logging in, links in views and login.html
    path("login/", views.LoginView, name="login"),

    # An url for registering, links in views and register.html
    path('register/', views.register, name="register"),


    # Creating a path for the createTask function in views.py in order to create a task .
    path('create_task', views.create_task, name='create_task'),


    # Creating a path for the viewTask function in views.py in order to view task.
    path('view_task/<str:pk>/', views.view_task, name='view_task'),

    # Creating a path for the update_task function in views.py in order to update a task.
    path('update_task/<str:pk>/', views.update_task, name='update_task'),

    # A path for the deleteTask function in views.py in order to delete a task using the primary key.
    path('delete/<str:pk>/', views.delete_task, name='delete_task'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taskly/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=100, null=True)
    content = models.CharField(max_length=1000, null=True, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True, null=True)
    due_date = models.DateTimeField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

taskly/views.py
from crispy_forms.helper import FormHelper
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .files import LoginForm, NewUserForm, CreateTask
from django.contrib import messages
from .models import Task
from .files import TaskForm

# Create your views here.
@login_required()
def index(request):
    tasks = Task.objects.all().filter(user=request.user)
    return render(request, 'index.html', {'tasks':tasks})


def LoginView(request):
    """
    If the request is a POST request, then we create a LoginForm object with the request and the POST
    data.
    If the form is valid, then we get the username and password from the form, authenticate the user,
    and log them in.
    If the request is not a POST request, then we create an empty LoginForm object.
    In either case, we render the login.html template with the form.

    :param request: The request object is passed to the view by Django. It contains all the information
    about the current request
    :return: The login_view function is returning a render function.
    """
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('taskly:dashboard')
    else:
        form = LoginForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


class LogoutView(generic.base.RedirectView):
    """
    It's a subclass of RedirectView that logs out the user and then redirects to the URL specified by
    the url attribute
    """
    url = reverse_lazy('taskly:index')

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('taskly:login')


def register(request):
    """
    If the request is a POST request, then validate the form and save the user. If the form is valid,
    then log the user in and redirect them to the login page. If the form is not valid, then display an
    error message. If the request is not a POST request, then display the form.

    :param request: The current request object
    :return: The form is being returned.
    """
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("taskly:login")
        else:
            messages.error(request, "Unsuccessful Registration . Invalid information.")
    else:
        form = NewUserForm()

        # Use the Crispy Forms helper to add Bootstrap styling to the form
    form.helper = FormHelper()
    form.helper.form_class = 'form-group'
    form.helper.label_class = 'form-label'
    form.helper.field_class = 'form-control'
    return render(request=request, template_name="register.html", context={"register_form": form})



    
@login_required(login_url='my_login')
def create_task(request):
    """
    This function creates a new task for a logged-in user using a form and saves it to the database.

    :param request: The HTTP request object that contains information about the current request,
    including the user making the request, the HTTP method used (GET, POST, etc.), and any data
    submitted with the request
    :return: This function returns a rendered HTML template named 'createTask.html' with a context
    dictionary containing a TaskForm object. If the request method is POST and the form is valid, it
    creates a new task object with the user who made the request and redirects to the dashboard page.
    """
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('taskly:dashboard')
    else:
        form = TaskForm()

    context = {'form': form}
    return render(request, 'createTask.html', context)


@login_required(login_url='my_login')
def view_task(request, pk):
    """
    This is a Python function that requires login authentication to view a specific task and renders it
    on a web page.
    
    :param request: The HTTP request object that contains information about the current request, such as
    the user making the request, the HTTP method used, and any data submitted with the request
    :param pk: pk stands for "primary key" and is a unique identifier for a specific instance of a model
    in a database. In this case, it is used to retrieve a specific Task object from the database based
    on its primary key value
    :return: The view_task function is returning an HTTP response that renders the 'viewTask.html'
    template with the context dictionary containing the task object retrieved using the pk parameter.
    The function is decorated with the login_required decorator, which means that the user must be
    authenticated to access this view. If the user is not authenticated, they will be redirected to the
    'my_login' URL.
    """
    task = get_object_or_404(Task, pk=pk)
    context = {'task': task}
    return render(request, 'viewTask.html', context=context)


@login_required(login_url='my_login')
def update_task(request, pk):
    """
    This function updates a task instance in the database and redirects to the view task page.
    
    :param request: The HTTP request object that contains information about the current request, such as
    the user making the request and any data submitted with the request
    :param pk: pk stands for "primary key" and is used to identify a specific instance of a model in the
    database. In this case, it is used to identify the specific task that needs to be updated
    :return: a rendered HTML template 'updateTask.html' with a context dictionary containing a form and
    a task object. If the request method is POST and the form is valid, the function redirects to the
    'view_task' view with the primary key of the updated task as a parameter.
    """
    task = Task.objects.get(id=pk)
    # this allows us to work on the specific instance of the task (code below)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        # if the item is valid then we update the database

        if form.is_valid():
            form.save()
            # then we return the views tasks to see if our database is updated
            return redirect('taskly:view_task', pk=pk)
    else:
        form = TaskForm(instance=task)
    context = {'form': form, 'task': task}
    return render(request, 'updateTask.html', context=context)


@login_required(login_url='my_login')
def delete_task(request, pk):
    """
    This function deletes a task object from the database and redirects to the dashboard page.
    
    :param request: The HTTP request object that contains information about the current request, such as
    the user making the request, the HTTP method used, and any data submitted with the request
    :param pk: pk stands for primary key, which is a unique identifier for each record in a database
    table. In this case, it is used to fetch the specific task object from the database that the user
    wants to delete
    :return: a rendered HTML template 'deleteTask.html' with the context of the task object. If the
    request method is POST, the function deletes the task object and redirects to the 'dashboard' page.
    """
    # Fetching the task object from the database using the primary key
    task = get_object_or_404(Task, pk=pk)

    if request.method == 'POST':
        # If the user confirms the deletion, then delete the task object
        task.delete()
        # Redirect to the viewTask page after deletion
        return redirect('taskly:dashboard')

    # Render the deleteTask.html template with the task object as context
    context = {'task': task}
    return render(request, 'deleteTask.html', context=context)

taskly/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width-device-width, initial-scale=1, maximum-scale=1" >
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/litera/bootstrap.min.css">
    <title>Taskly Home Page</title>
</head>


<header>
      <nav class="navbar navbar-expand-lg navbar-light custom-bg">
      <a class="navbar-brand" href="#">Taskly Status Bar ==></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">

            <li class="nav-item">
              <a class="nav-link" href="{% url 'taskly:register' %}">Register</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'taskly:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'taskly:login' %}">Login</a>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'taskly:dashboard' %}">Dashboard</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href=""></a>
                </li>
            {% endif %}



        </ul>
      </div>
    </nav>
    <br><br>
</header>



<body>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>



</body>

</html>

taskly/templates/createTask.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="backdrop">
<div class="container  bg-white shadow-md py-5 form-layout">
     <h3>Create Task</h3>
<form method="POST" action="{% url 'taskly:create_task' %}" autocomplete="off">
    {% csrf_token %}

    {{ form|crispy }}

    <br>
    <input class="btn btn-primary navbar btn" type="submit" value="Submit">

</form>

</div>
</div>
{% endblock content %}

taskly/templates/deleteTask.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container bg-white shadow-md py-5 form-layout">
  <h3>Delete Task</h3>
  <hr>
  <p>Are you sure you want to delete this task?</p>
  <p>{{ task.title }}</p>
  <form method="POST" action="{% url 'taskly:delete_task' pk=task.pk %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete it</button>
    <a href="{% url 'taskly:view_task' pk=task.pk %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock content %}

taskly/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{% block content %}
<h1>Taskly..... </h1>
<h2>A Home For Your Tasks</h2>

    <br><br>
    <div class="backdrop">
        <h1>Welcome to Taskly  {{ username }}</h1>
            <div class="backdrop">

            </div>
    </div>
    <br>

<a href="{% url 'taskly:create_task' %}" class="btn btn-primary mb-2">Add Task</a>

<table class="table">
    <thead>
        <tr>
            <th>Task Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Due Date</th>
            <th>Date Posted</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.title }}</td>
            <td>{{ task.content }}</td>
            <td>
                {% if task.due_date %}
                    {% if task.due_date < task.date_posted %}
                        Overdue
                    {% else %}
                        Pending
                    {% endif %}
                {% else %}
                    No Due Date
                {% endif %}
            </td>
            <td>{{ task.due_date }}</td>
            <td>{{ task.date_posted }}</td>

            <td>
                <a href="{% url 'taskly:view_task' task.pk %}" class="btn btn-secondary btn-sm">View</a>
                <a href="{% url 'taskly:update_task' task.pk %}" class="btn btn-primary btn-sm">Edit</a>
                <form action="{% url 'taskly:delete_task' task.pk %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <a href="{% url 'taskly:delete_task' task.id %}" class="btn btn-danger btn-sm">Delete</a>
                </form>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No tasks found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


</html>

taskly/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container py-5">
        <h1>Login Section</h1>
        <form method="post">
            {% csrf_token %}
            {{ login_form.as_p }}
            <button class="btn btn-primary" type="submit">LOGIN</button>
        </form>
        <p class="text-center">Don't have an account yet? Then register <a href="{% url 'taskly:register' %}">here!</a> </p>
    </div>
{% endblock content %}

taskly/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<html lang="en">

<body>
{% block content %}
<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">Do you already have an account? Then <a href="{% url 'taskly:login' %}">login</a> instead.</p>
</div>

{% endblock content %}
</body>
</html>

taskly/templates/updateTask.html
{% extends "index.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="backdrop">
    <h3>Update Task</h3>
        <div class="container  bg-white shadow-md py-5 form-layout">
            <form method="POST" action="{% url 'taskly:update_task' pk=task.pk %}" autocomplete="off">
                {% csrf_token %}

                {{ form.title|as_crispy_field }}
                <br><br>
                {{ form.content| as_crispy_field }}
                <br><br>

                <br>
                <input class="btn btn-primary navbar btn" type="submit" value="SUBMIT">

            </form>
        </div>
    </div>
{% endblock content %}

taskly/templates/viewTask.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
        <br><br><h3 style="align-content: center">My Task</h3><br>
        <div class="backdrop">

         <div class="container  bg-white shadow-md py-5 form-layout">
             <h2>{{ task.title }}</h2><br>
             {{ task.content }}<br><br>

             <a href="{% url 'taskly:update_task' task.id %}" class="btn btn-primary btn-lg">Update</a>
             <a href="{% url 'taskly:delete_task' task.id %}" class="btn btn-primary btn-lg">Delete</a>


         </div>

         <br><br>
        </div>
             <br><br>
{% endblock content %}